.\"	dhcpd.conf.5
.\"
.\" Copyright (c) 1995, 1996 The Internet Software Consortium.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\"
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of The Internet Software Consortium nor the names
.\"    of its contributors may be used to endorse or promote products derived
.\"    from this software without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE INTERNET SOFTWARE CONSORTIUM AND
.\" CONTRIBUTORS ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
.\" INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
.\" DISCLAIMED.  IN NO EVENT SHALL THE INTERNET SOFTWARE CONSORTIUM OR
.\" CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
.\" SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
.\" LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF
.\" USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
.\" ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
.\" OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
.\" OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\" This software has been written for the Internet Software Consortium
.\" by Ted Lemon <mellon@fugue.com> in cooperation with Vixie
.\" Enterprises.  To learn more about the Internet Software Consortium,
.\" see ``http://www.isc.org/isc''.  To learn more about Vixie
.\" Enterprises, see ``http://www.vix.com''.
.TH dhcpd.conf(5)
.SH NAME
dhcpd.conf - dhcpd configuration file
.SH DESCRIPTION
The dhcpd.conf file contains configuration information for
.IR dhcpd(8),
the Dynamic Host Configuration Protocol daemon.   A primer on configuring
dhcpd is included in dhcpd(8).
This document describes the format of the file in detail, and is
probably a better reference than a primer.
.PP
The dhcpd.conf
file is a free-form ASCII text file.   It is parsed by a
recursive-descent parser.   Statements in the file may contain extra
tabs and newlines for formatting purposes.   Each statement in the
file is terminated by a semicolon.   Keywords in the file are
case-insensitive.
.PP
There are currently two statements that can
meaningfully appear in the file\(emthe
.IR subnet
statement, and the
.IR host
statement.
.SH The SUBNET statement
.B subnet
.I subnet-number
.B netmask
.I netmask
[
.I clauses
];
.PP
.I subnet-number
should be an IP address or DNS name which resolves to the subnet
number of the subnet being described.
.I netmask
should be an IP address or DNS name which resolves to the subnet mask
of the subnet being described. These are the only required fields
in a subnet declaration, although it may be desirable to add one or
more of the following clauses.
.PP
Subnets for which addresses will be dynamically allocated must have
one or more addresses reserved for future allocation by dhcpd.
These addresses are allocated using the
.IR range
clause.
.PP
.B range
.I lowest-address
.I highest-address
.PP
.I lowest-address
should be the lowest address in the range that may be assigned by
dhcpd to a DHCP client.
.I highest-address
should be the highest address in the range that may be assigned by
dhcpd.   If there is only one address in a range, it must be specified
as both the lowest and highest addresses.  As many
.B range
clauses as are needed may be specified in any given
.B subnet
statement.
.PP
.B default-lease-time
.I time
.PP
.I time
should be the expiration time in seconds that will be assigned to a
lease if the client requesting the lease does not ask for a specific
expiration time.   This clause may only appear once in each
.B subnet
statement.
.PP
.B max-lease-time
.I time
.PP
.I time
should be the maximum expiration time in seconds that will be assigned
to a lease if the client requesting the lease asks for a specific
expiration time.   This clause may only appear once in each
.B subnet
statement.
.PP
.B option
.I option-declaration
.PP
Any number of
.B option
clauses may appear in a subnet statement.   The syntax of
option declarations is described later in this document.
.SH The HOST statement
.B host
.I hostname
.Op Ar clauses ;
.PP
There must be at least one
.B host
statement for every BOOTP client that is to be served.   
.B host
statements may also be specified for DHCP clients, although this is
not required.   If it is desirable to be able to boot a DHCP or BOOTP
client on more than one subnet with fixed addresses, more than one
address may be specified in the
.B fixed-address
clause, or more than one
.B host
statement may be specified.   If
client-specific boot parameters must change based on the network
to which the client is attached, then multiple 
.B host
statements should
be used.   If a client is to be booted using a fixed address if it's
possible, but should be allocated a dynamic address otherwise, then a
.B host
statement must be specified without a
.B fixed-address
clause.
.I hostname
should be a name identifying the host.   It is for labelling purposes
only, and is not used in the BOOTP protocol.
.PP
.B hardware
.I hardware-type
.I hardware-address
.PP
In order for a BOOTP client to be recognized, its network hardware
address must be declared using a
.B hardware
clause in the
.B host
statement.   Only one such clause can appear in any host statement.
.I hardware-type
must be the name of a physical hardware interface type.   Currently,
only the
.B ethernet
type is recognized, although support for
.B token-ring
and
.B fddi
hardware types will be added soon.
The
.I hardware-address
should be a set of hexadecimal octets (numbers from 0 through ff)
seperated by colons.
.PP
.B filename
.I filename
.PP
If the BOOTP client needs to load a boot file (for example, a kernel
or configuration file), the name of this file may be provided to the
client using the
.B filename
clause.   The
.I filename
should be a filename recognizable to whatever file transfer protocol
the client can be expected to use to load the file.
.PP
.B fixed-address
.I address
[,
.I address
]
.PP
BOOTP clients must be assigned fixed IP addresses.   DHCP clients may
optionally be assigned a fixed address.   The
.B fixed-address
clause is used to associate one or more fixed IP address with a BOOTP
or DHCP client.   If more than one address is supplied, the client may
be booted on each network for which an address is specified.
Multiple addresses on the same network should not be specified.
.I address
should be either an IP address or a DNS name which resolves to a
single IP address.
.PP
.B option
.I option-declaration
.PP
Any number of
.B
option clauses may appear in a host statement.   The syntax of
option declarations is described later in this document.   If an
option clause in a
.B host
statement conflicts with an option clause in the
.B subnet
statement for the subnet containing that host, the option clause in
the
.B host
statement is used.
.PP
.SH Option Declarations
.PP
Option declarations always start with the
.B option
keyword, followed by an option name, followed by option data.   The
option names and data formats are described below.   Many of the
options described below which set IP or TCP parameters have default
values which will generally work perfectly well, so only those options
whose values must be set explicitly should be included in.
B subnet
or
.B host
statements.
.PP
Option data comes in a variety of formats.   In order to avoid having
to explain the formats along with each option definition below, a
number of data types have been defined.
.PP
The ip-address data type can be entered either as an explicit IP
address (e.g., 239.254.197.10) or as a domain name (e.g.,
haagen.isc.org).  When entering a domain name, be sure that that
domain name resolves to a single IP address.
.PP
The int32 data type specifies a signed 32-bit integer.   The uint32
data type specifies an unsigned 32-bit integer.   The int16 and uint16
data types specify signed and unsigned 16-bit integers.   The int8 and
uint8 data types specify signed and unsigned 8-bit integers.
Unsigned 8-bit integers are also sometimes referred to as octets.
.PP
The string data type specifies an NVT ASCII string, which must be
enclosed in double quotes - for example, to specify a domain-name
option, the syntax would be
.nf
.sp 1
	option domain-name "isc.org"
.fi
.PP
The flag data type specifies a one-bit (boolean) number.
.PP
The data-string data type specifies either an NVT ASCII string
enclosed in double quotes, or a series of octets specified in
hexadecimal, seperated by colons.   For example:
.nf
.sp 1
	option client-identifier "CLIENT-FOO"
or
	option client-identifier 43:4c:49:45:54:2d:46:4f:4f
.fi
.PP
The documentation for the various options mentioned below is taken
from the latest IETF draft document on DHCP options.
.PP
.B option
.B subnet-mask
.I ip-address
.PP
The subnet mask option specifies the client's subnet mask as per RFC
950.
.PP
.B option
.B time-offset
.I int32
.PP
The time-offset option specifies the offset of the client's subnet in
seconds from Coordinated Universal Time (UTC).
.PP
.B option
.B routers
.I ip-address
[,
.I ip-address
.I ...
]
.PP
The routers option specifies a list of IP addresses for routers on the
client's subnet.  Routers should be listed in order of preference.
.PP
.B option
.B time-servers
.I ip-address
[,
.I ip-address
.I ...
]
.PP
The time-server option specifies a list of RFC 868 time servers
available to the client.  Servers should be listed in order of
preference.
.PP
.B option
.B name-servers
.I ip-address
[,
.I ip-address
.I ...
]
.PP
The name-servers option specifies a list of IEN 116 name servers
available to the client.  Servers should be listed in order of
preference.
.PP
.B option
.B domain-name-servers
.I ip-address
[,
.I ip-address
.I ...
]
.PP
The domain-name-servers option specifies a list of Domain Name System
(STD 13, RFC 1035) name servers available to the client.  Servers
should be listed in order of preference.
.PP
.B option
.B log-servers
.I ip-address
[,
.I ip-address
.I ...
]
.PP
The log-server option specifies a list of MIT-LCS UDP log servers
available to the client.  Servers should be listed in order of
preference.
.PP
.B option
.B cookie-servers
.I ip-address
[,
.I ip-address
.I ...
]
.PP
The cookie server option specifies a list of RFC 865 cookie
servers available to the client.  Servers should be listed in order
of preference.
.PP
.B option
.B lpr-servers
.I ip-address 
[,
.I ip-address
.I ... 
]
.PP
The LPR server option specifies a list of RFC 1179 line printer
servers available to the client.  Servers should be listed in order
of preference.
.PP
.B option
.B impress-servers
.I ip-address
[,
.I ip-address
.I ...
]
.PP
The impress-server option specifies a list of Imagen Impress servers
available to the client.  Servers should be listed in order of
preference.
.PP
.B option
.B resource-location-servers
.I ip-address
[,
.I ip-address
.I ...
]
.PP
This option specifies a list of RFC 887 Resource Location
servers available to the client.  Servers should be listed in order
of preference.
.PP
.B option
.B host-name
.I string
.PP
This option specifies the name of the client.  The name may or may
not be qualified with the local domain name (it is preferable to use
the domain-name option to specify the domain name).  See RFC 1035 for
character set restrictions.
.PP
.B option
.B boot-size
.I uint16
.PP
This option specifies the length in 512-octet blocks of the default
boot image for the client.
.PP
.B option
.B merit-dump
.I string
.PP
This option specifies the path-name of a file to which the client's
core image should be dumped in the event the client crashes.  The
path is formatted as a character string consisting of characters from
the NVT ASCII character set.
.PP
.B option
.B domain-name
.I string
.PP
This option specifies the domain name that client should use when
resolving hostnames via the Domain Name System.
.PP
.B option
.B swap-server
.I ip-address
.PP
This specifies the IP address of the client's swap server.
.PP
.B option
.B root-path
.I string
.PP
This option specifies the path-name that contains the client's root
disk.  The path is formatted as a character string consisting of
characters from the NVT ASCII character set.
.PP
.B option
.B ip-forwarding
.I flag
.PP
This option specifies whether the client should configure its IP
layer for packet forwarding.  A value of 0 means disable IP
forwarding, and a value of 1 means enable IP forwarding.
.PP
.B option
.B non-local-source-routing
.I flag
.PP
This option specifies whether the client should configure its IP
layer to allow forwarding of datagrams with non-local source routes
(see Section 3.3.5 of [4] for a discussion of this topic).  A value
of 0 means disallow forwarding of such datagrams, and a value of 1
means allow forwarding.
.PP
.B option
.B policy-filter
.I ip-address ip-address
[,
.I ip-address ip-address
.I ...
]
.PP
This option specifies policy filters for non-local source routing.
The filters consist of a list of IP addresses and masks which specify
destination/mask pairs with which to filter incoming source routes.
.PP
Any source routed datagram whose next-hop address does not match one
of the filters should be discarded by the client.
.PP
See STD 3 (RFC1122) for further information.
.PP
.B option
.B max-dgram-reassembly
.I uint16
.PP
This option specifies the maximum size datagram that the client
should be prepared to reassemble.  The minimum value legal value is
576.
.PP
.B option
.B default-ip-ttl
.I uint8
.PP
This option specifies the default time-to-live that the client should
use on outgoing datagrams.
.PP
.B option
.B path-mtu-aging-timeout
.I uint32
.PP
This option specifies the timeout (in seconds) to use when aging Path
MTU values discovered by the mechanism defined in RFC 1191.
.PP
.B option
.B path-mtu-plateau-table
.I uint16
[,
.I uint16
.I ...
]
.PP
This option specifies a table of MTU sizes to use when performing
Path MTU Discovery as defined in RFC 1191.  The table is formatted as
a list of 16-bit unsigned integers, ordered from smallest to largest.
The minimum MTU value cannot be smaller than 68.
.PP
.B option
.B interface-mtu
.I uint16
.PP
This option specifies the MTU to use on this interface.   The minimum
legal value for the MTU is 68.
.PP
.B option
.B all-subnets-local
.I flag
This option specifies whether or not the client may assume that all
subnets of the IP network to which the client is connected use the
same MTU as the subnet of that network to which the client is
directly connected.  A value of 1 indicates that all subnets share
the same MTU.  A value of 0 means that the client should assume that
some subnets of the directly connected network may have smaller MTUs.
.PP
.B option
.B broadcast-address
.I ip-address
.PP
This option specifies the broadcast address in use on the client's
subnet.  Legal values for broadcast addresses are specified in
section 3.2.1.3 of STD 3 (RFC1122).
.PP
.B option
.B perform-mask-discovery
.I flag
.PP
This option specifies whether or not the client should perform subnet
mask discovery using ICMP.  A value of 0 indicates that the client
should not perform mask discovery.  A value of 1 means that the
client should perform mask discovery.
.PP
.B option
.B mask-supplier
.I flag
.PP
This option specifies whether or not the client should respond to
subnet mask requests using ICMP.  A value of 0 indicates that the
client should not respond.  A value of 1 means that the client should
respond.
.PP
.B option
.B router-discovery
.I flag
.PP
This option specifies whether or not the client should solicit
routers using the Router Discovery mechanism defined in RFC 1256.
A value of 0 indicates that the client should not perform
router discovery.  A value of 1 means that the client should perform
router discovery.
.PP
.B option
.B router-solicitation-address
.I ip-address
.PP
This option specifies the address to which the client should transmit
router solicitation requests.
.PP
.B option
.B static-routes
.I ip-address ip-address
[,
.I ip-address ip-address
.I ...
]
.PP
This option specifies a list of static routes that the client should
install in its routing cache.  If multiple routes to the same
destination are specified, they are listed in descending order of
priority.
.PP
The routes consist of a list of IP address pairs.  The first address
is the destination address, and the second address is the router for
the destination.
.PP
The default route (0.0.0.0) is an illegal destination for a static
route.  To specify the default route, use the
.B routers
option.
.PP
.B option
.B trailer-encapsulation
.I flag
.PP
This option specifies whether or not the client should negotiate the
use of trailers (RFC 893 [14]) when using the ARP protocol.  A value
of 0 indicates that the client should not attempt to use trailers.  A
value of 1 means that the client should attempt to use trailers.
.PP
.B option
.B arp-cache-timeout
.I uint32
.PP
This option specifies the timeout in seconds for ARP cache entries.
.PP
.B option
.B ieee802-3-encapsulation
.I flag
.PP
This option specifies whether or not the client should use Ethernet
Version 2 (RFC 894) or IEEE 802.3 (RFC 1042) encapsulation if the
interface is an Ethernet.  A value of 0 indicates that the client
should use RFC 894 encapsulation.  A value of 1 means that the client
should use RFC 1042 encapsulation.
.PP
.B option
.B default-tcp-ttl
.I uint8
.PP
This option specifies the default TTL that the client should use when
sending TCP segments.  The minimum value is 1.
.PP
.B option
.B tcp-keepalive-interval
.I uint32
.PP
This option specifies the interval (in seconds) that the client TCP
should wait before sending a keepalive message on a TCP connection.
The time is specified as a 32-bit unsigned integer.  A value of zero
indicates that the client should not generate keepalive messages on
connections unless specifically requested by an application.
.PP
.B option
.B tcp-keepalive-garbage
.I flag
.PP
This option specifies the whether or not the client should send TCP
keepalive messages with a octet of garbage for compatibility with
older implementations.  A value of 0 indicates that a garbage octet
should not be sent. A value of 1 indicates that a garbage octet
should be sent.
.PP
.B option
.B nis-domain
.I string
.PP
This option specifies the name of the client's NIS (Sun Network
Information Services) domain.  The domain is formatted as a character
string consisting of characters from the NVT ASCII character set.
.PP
.B option
.B nis-servers
.I ip-address
[,
.I ip-address
.I ...
]
.PP
This option specifies a list of IP addresses indicating NIS servers
available to the client.  Servers should be listed in order of
preference.
.PP
.B option
.B ntp-servers
.I ip-address
[,
.I ip-address
.I ...
]
.PP
This option specifies a list of IP addresses indicating NTP (RFC 1035)
servers available to the client.  Servers should be listed in order
of preference.
.PP
.B option
.B netbios-name-servers
.I ip-address
[,
.I ip-address
.I ...
]
.PP
The NetBIOS name server (NBNS) option specifies a list of RFC
1001/1002 NBNS name servers listed in order of preference.
.PP
.B option
.B netbios-dd-server
.I ip-address
[,
.I ip-address
.I ...
]
.PP
The NetBIOS datagram distribution server (NBDD) option specifies a
list of RFC 1001/1002 NBDD servers listed in order of preference.
.PP
.B option
.B netbios-node-type
.I uint8
.PP
The NetBIOS node type option allows NetBIOS over TCP/IP clients which
are configurable to be configured as described in RFC 1001/1002.  The
value is specified as a single octet which identifies the client type.
A value of 1 corresponds to a NetBIOS B-node; a value of 2 corresponds
to a P-node; a value of 4 corresponds to an M-node; a value of 8
corresponds to an H-node.
.PP
.B option
.B netbios-scope
.I string
.PP
The NetBIOS scope option specifies the NetBIOS over TCP/IP scope
parameter for the client as specified in RFC 1001/1002. See RFC1001,
RFC1002, and RFC1035 for character-set restrictions.
.PP
.B option
.B font-servers
.I ip-address
[,
.I ip-address
.I ...
]
.PP
This option specifies a list of X Window System Font servers available
to the client. Servers should be listed in order of preference.
.PP
.B option
.B x-display-manager
.I ip-address
[,
.I ip-address
.I ...
]
.PP
This option specifies a list of systems that are running the X Window
System Display Manager and are available to the client.  Addresses
should be listed in order of preference.
.PP
.B option
.B dhcp-client-identifier
.I data-string
.PP
This option can be used to specify the a DHCP client identifier in a
host declaration, so that dhcpd can find the host record by matching
against the client identifier.
.SH SEE ALSO
dhcpd.conf(5), dhcpd.leases(5)
.SH AUTHOR
.B dhcpd(8)
was written by Ted Lemon <mellon@vix.com>
under a contract with Vixie Labs.   Funding
for this project was provided by the Internet Software Corporation.
Information about the Internet Software Consortium can be found at
.B http://www.isc.org/isc.
