.\"	dhcpd.8
.\"
.\" Copyright (c) 1995, 1996 The Internet Software Consortium.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\"
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of The Internet Software Consortium nor the names
.\"    of its contributors may be used to endorse or promote products derived
.\"    from this software without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE INTERNET SOFTWARE CONSORTIUM AND
.\" CONTRIBUTORS ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
.\" INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
.\" DISCLAIMED.  IN NO EVENT SHALL THE INTERNET SOFTWARE CONSORTIUM OR
.\" CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
.\" SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
.\" LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF
.\" USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
.\" ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
.\" OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
.\" OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\" This software has been written for the Internet Software Consortium
.\" by Ted Lemon <mellon@fugue.com> in cooperation with Vixie
.\" Enterprises.  To learn more about the Internet Software Consortium,
.\" see ``http://www.isc.org/isc''.  To learn more about Vixie
.\" Enterprises, see ``http://www.vix.com''.
.Dd March 5, 1996
.Dt dhcpd 8
.Sh NAME
.Nm dhcpd
.Nd Dynamic Host Configuration Protocol server
.Sh SYNOPSIS
.Nm dhcpd
.Op Fl p port
.Sh DESCRIPTION
.Xr dhcpd 8
implements the Dynamic Host Configuration Protocol (DHCP) and
the Internet Bootstrap Protocol (BOOTP).  DHCP allows hosts on a
TCP/IP network to request and be assigned IP addresses, and also to
discover information about the network to which they are attached.
BOOTP provides similar but much more limited functionality.
.Sh OPERATION
.Pp
The DHCP protocol allows a host which is unknown to the network
administrator to be automatically assigned a new IP address out of a
pool of IP addresses for its network.   In order for this to work, the
network administrator allocates address pools in each subnet and
enters them into the
.Xr dhcpd.conf 5
file.
.Pp
On startup, dhcpd reads the
.Nm dhcpd.conf
file and keeps the list of available addresses on each subnet in
memory.  When a host requests an address using the DHCP protocol,
dhcpd allocates an address for it.  Each such host is assigned a
lease, which expires after an amount of time chosen by the
administrator (by default, one day).  As leases expire, the hosts to
which they are assigned are expected to renew the leases if they wish
to continue to use the addresses.   Once a lease has expired, the host
to which that lease is assigned is no longer permitted to use the IP
address assigned to it.
.Pp
In order to keep track of leases across system reboots and server
restarts,
.Nm dhcpd
keeps a list of leases it has assigned in the
.Xr dhcpd.leases 5
file.   Before dhcpd grants a lease to a host, it records the lease in
this file and makes sure that the contents of the file are flushed to
disk.   This ensures that even in the event of a system crash,
.Nm dhcpd
will not forget about a lease that it has assigned.   On startup,
after reading the
.Nm dhcpd.conf
file,
.Nm dhcpd
reads the
.Nm dhcpd.leases
file to refresh its memory about what leases have been assigned.
.Pp
New leases are appended to the end of the
.Nm dhcpd.leases
file.   In order to prevent the file from becoming arbitrarily large,
from time to time
.Nm dhcpd
creates a new
.Nm dhcpd.leases
file from its in-core lease database.  Once this file has been written
to disk, the old file is renamed
.Nm dhcpd.leases~ ,
and the new file is renamed
.Nm dhcpd.leases .
If the system crashes in the middle of this process,
whichever
.Nm dhcpd.leases
file remains will contain all the lease information, so there is no
need for a special crash recovery process.
.Pp
BOOTP support is also provided by this server.   Unlike DHCP, the
BOOTP protocol requires that the server know the hardware address of
the client that is to be booted.   The network administrator must
determine that address, allocate an IP address for the client, and
enter that information into the
.Nm dhcpd.conf
file.
.Pp
Whenever changes are made to the
.Nm dhcpd.conf
file,
.Nm dhcpd
must be restarted.   To restart
.Nm dhcpd ,
send signal 15 to the process ID contained in
.Nm /var/run/dhcpd.pid ,
and then re-invoke
.Nm dhcpd .

.Sh CONFIGURATION
The syntax of the
.Xr dhcpd.conf 8
file is discussed seperately.   This section should be used as an
overview of the configuration process, and the
.Xr dhcpd.conf 8
documentation should be consulted for detailed reference information.
.Pp
.Sh Subnets
.Xr dhcpd 8
needs to know the subnet numbers and netmasks of all subnets for which
it will be providing service.   In addition, in order to dynamically
allocate addresses, it must be assigned one or more ranges of
addresses on each subnet which it can in turn assign to client hosts
as they boot.   Thus, a very simple configuration providing DHCP
support might look like this:
.nf
.sp 1
	subnet 239.252.197.0 netmask 255.255.255.0
	  range 239.252.197.10 239.252.197.250;
.fi
.Pp
Multiple address ranges may be specified like this:
.nf
.sp 1
	subnet 239.252.197.0 netmask 255.255.255.0
	  range 239.252.197.10 239.252.197.107
	  range 239.252.197.113 239.252.197.250;
.fi
.Pp
If a subnet will only be provided with BOOTP service and no dynamic
address assignment, the range clause can be left out entirely, but the
subnet statement must appear.
.Pp
.Sh Lease Lengths
DHCP leases can be assigned almost any length from zero seconds to
infinity.   What lease length makes sense for any given subnet, or for
any given installation, will vary depending on the kinds of hosts
being served.
.Pp
For example, in an office environment where systems are added from
time to time and removed from time to time, but move relatively
infrequently, it might make sense to allow lease times of a month of
more.   In a final test environment on a manufacturing floor, it may
make more sense to assign a maximum lease length of 30 minutes -
enough time to go through a simple test procedure on a network
appliance before packaging it up for delivery.
.Pp
It is possible to specify two lease lengths: the default length that
will be assigned if a client doesn't ask for any particular lease
length, and a maximum lease length.   These are specified as clauses
to the subnet command:
.nf
.sp 1
	subnet 239.252.197.0 netmask 255.255.255.0
	  range 239.252.197.10 239.252.197.107
	  default-lease-time 600
	  max-lease-time 7200;
.fi
.Pp
This particular subnet declaration specifies a default lease time of
600 seconds (ten minutes), and a maximum lease time of 7200 seconds
(two hours).   Other common values would be 86400 (one day), 604800
(one week) and 2592000 (30 days).
.Pp
Each subnet need not have the same lease\(emin the case of an office
environment and a manufacturing environment served by the same DHCP
server, it might make sense to have widely disparate values for
default and maximum lease times on each subnet.
.Sh BOOTP Support
Each BOOTP client must be explicitly declared in the
.Nm dhcpd.conf
file.   A very basic client declaration will specify the client
network interface's hardware address and the IP address to assign to
that client.   If the client needs to be able to load a boot file from
the server, that file's name must be specified.   A simple bootp
client declaration might look like this:
.nf
.sp 1
	host haagen hardware ethernet 08:00:2b:4c:59:23
	  fixed-address 239.252.197.9
	  filename "/tftpboot/haagen.boot";
.fi
.Sh Options
DHCP (and also BOOTP with Vendor Extensions) provide a mechanism
whereby the server can provide the client with information about how
to configure its network interface (e.g., subnet mask), and also how
the client can access various network services (e.g., DNS, IP routers,
and so on).
.Pp
These options can be specified on a per-subnet basis, and, for BOOTP
clients, also on a per-client basis.   In the event that a BOOTP
client declaration specifies options that are also specified in its
subnet declaration, the options specified in the client declaration
take precedence.   An reasonably complete DHCP configuration might
look something like this:
.nf
.sp 1
	subnet 239.252.197.0 netmask 255.255.255.0
	  range 239.252.197.10 239.252.197.250
	  default-lease-time 600 max-lease-time 7200
	  option subnet-mask 255.255.255.0
	  option broadcast-address 239.252.197.255
	  option routers 239.252.197.1
	  option domain-name-servers 239.252.197.2, 239.252.197.3
	  option domain-name "isc.org";
.fi
.Pp
A bootp host on that subnet that needs to be in a different domain and
use a different name server might be declared as follows:
.nf
.sp 1
	host haagen hardware ethernet 08:00:2b:4c:59:23
	  fixed-address 239.252.197.9
	  filename "/tftpboot/haagen.boot"
	  option domain-name-servers 192.5.5.1
	  option domain-name "vix.com";
.fi
.Pp
A complete list of DHCP Options and their syntaxes is provided in
.Xr dhcpd.conf 5 .
.Sh FILES
.Nm /etc/dhcpd.conf ,
.Nm /etc/dhcpd.leases ,
.Nm /var/run/dhcpd.pid ,
.Nm /etc/dhcpd.leases~ .
.Sh SEE ALSO
.Xr dhcpd.conf 5 ,
.Xr dhcpd.leases 5
.Sh AUTHOR
.Xr dhcpd 8
was written by Ted Lemon
.Nm <mellon@vix.com>
under a contract with Vixie Labs.   Funding
for this project was provided by the Internet Software Corporation.
Information about the Internet Software Consortium can be found at
.Nm http://www.isc.org/isc .
